# Generated by Django 2.1.4 on 2018-12-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181207_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
