# Generated by Django 2.1.4 on 2018-12-30 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20181230_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='name',
        ),
    ]
