# Generated by Django 2.1.4 on 2019-01-03 08:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_registered',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
