# Generated by Django 2.1.4 on 2020-06-07 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_profile_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='website',
        ),
    ]
