# Generated by Django 2.1.4 on 2018-12-08 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='speciality',
        ),
    ]
