# Generated by Django 2.1.4 on 2018-12-09 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_deal_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='deals.City'),
        ),
        migrations.AddField(
            model_name='deal',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='deals.Country'),
        ),
    ]
