# Generated by Django 2.1.4 on 2020-05-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0005_auto_20190109_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='deal_type',
            field=models.CharField(choices=[('project', 'project'), ('idea', 'idea')], default='project', max_length=50),
        ),
    ]
