# Generated by Django 2.1.4 on 2020-06-07 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0007_auto_20200514_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'ordering': ['-date_posted']},
        ),
    ]
