# Generated by Django 2.1.4 on 2020-06-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0008_auto_20200607_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='link',
            field=models.URLField(blank=True, max_length=128),
        ),
    ]
