# Generated by Django 2.1.4 on 2020-06-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0009_deal_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deal',
            old_name='link',
            new_name='presentation_link',
        ),
        migrations.AddField(
            model_name='deal',
            name='website_link',
            field=models.URLField(blank=True, max_length=128),
        ),
    ]
