# Generated by Django 2.1.4 on 2019-01-08 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comment',
            managers=[
            ],
        ),
    ]
